//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class banking_systemEntities : DbContext
    {
        public banking_systemEntities()
            : base("name=banking_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_transaction> customer_transaction { get; set; }
        public virtual DbSet<online_account> online_account { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
    }
}
